name: meta(deploys)

on:
  # Only runs webpack on master to save bundle size info into artifacts
  # which are then used on PRs to compare against
  push:
    branches:
      - master
  # TODO: don't run on PRs, only on master
  pull_request:

jobs:
  files-changed:
    name: files changed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check for file changes
        uses: getsentry/paths-filter@master
        id: changes
        with:
          list-files: shell
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Dispatch getsentry tests
        uses: actions/github-script@v5
        with:
          github-token: ${{ steps.token.outputs.token }}
          script: |
            require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/deploys`).updateChangeType({
              github,
              context,
              fileChanges: ${{ toJson(steps.changes.outputs) }}
            });
