name: meta(deploys)

on:
  # Only runs webpack on master to save bundle size info into artifacts
  # which are then used on PRs to compare against
  push:
    branches:
      - master
  # TODO: don't run on PRs, only on master
  pull_request:

jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Internal github app token
        id: token
        uses: getsentry/action-github-app-token@v1
        continue-on-error: true
        with:
          app_id: ${{ secrets.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - name: Check for frontend file changes
        uses: getsentry/paths-filter@master
        id: changes
        with:
          list-files: shell
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Dispatch getsentry tests
        uses: actions/github-script@v3
        with:
          github-token: ${{ steps.token.outputs.token }}
          script: |
            require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/deploys`).updateChangeType({
              github,
              context,
              fileChanges: ${{ toJson(steps.changes.outputs) }}
            });
