name: visual diff
on:
  workflow_run:
    workflows:
      - acceptance
    types:
      - completed

jobs:
  visual-diff:
    if: github.repository == 'getsentry/sentry'
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: getsentry/action-visual-snapshot@v2
        with:
          api-endpoint: 'https://sentry-visual-snapshot-staging-dwunkkvj6a-uc.a.run.app/api'
          api-token: ${{ secrets.VISUAL_SNAPSHOT_SECRET }}
          gcs-bucket: 'sentry-visual-snapshots'
          gcp-service-account-key: ${{ secrets.SNAPSHOT_GOOGLE_SERVICE_ACCOUNT_KEY }}
